name: fieldkit_ai
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.2
  google_fonts: ^6.2.1
  http: ^1.2.1
  flutter_markdown: ^0.6.18

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - lib/assets/pdfs/
    - lib/assets/icons/

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "lib/assets/icons/logo.png"
  web:
    generate: true
    image_path: "lib/assets/icons/logo.png"
  windows:
    generate: true
    image_path: "lib/assets/icons/logo.png"